version: '3.9'

services:
  web:
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      app-network:
        aliases:
          - web

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: course-back
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      app-network:
        aliases:
          - db

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge